### ISSUE TITLE
Reboot after nmcli connect

### ISSUE THREAD

**Issue by briansune** [lwfinger/rtl8723ds#41]
I had tried this driver and cross-compile.
The nmcli device wifi list working normal
But once I try to connect it works 1 out of 20 and could ping for a while.

Really need help/
No clue how to resolve such behavior

**Comment by lwfinger** [comment]
If it crashes your kernel, I need to see the BUG report.

**Comment by briansune** [comment]
May I ask how to extract the necessary report to help out?

**Comment by lwfinger** [comment]
If you have a second Linux system and you have a wired connection on the failing one, then netconsole is a good way.

If not, then open two terminal instances, and tile them vertically so that both can be seen. One sould be full width and occuly at least 2/3 of the screen. In the large one, run 'sudo dmesg -tw', and run your nmcli command in the smaller When it crashes, photograph the screen and attach the photo here.

**Comment by briansune** [comment]
My current developing environment is a ARM Ubuntu that runs on ARM-A7 CPU it is not a PC but a board like raspberry pi.
My current connection is only serial port.
I am not sure this is also apply to what method you had mentioned?

Thank you

**Comment by briansune** [comment]
`
sudo insmod 8723ds.ko
8723ds: loading out-of-tree module taints kernel.
RTW: module init start
RTW: rtl8723ds v5.1.1.5_20523.20161209_BTCOEX20161208-1212
RTW: build time: Jul 25 2023 15:56:33
RTW: rtl8723ds BT-Coex version = BTCOEX20161208-1212
RTW: sdio_init: sdio clk rate: 25000000
RTW: CHIP TYPE: RTL8723D
RTW: rtw_hal_config_rftype RF_Type is 3 TotalTxPath is 1
RTW: Chip Version Info: CHIP_8723D_Normal_Chip_TSMC_D_CUT_1T1R_RomVer(0)
RTW: SetHwReg: bMacPwrCtrlOn=1
RTW: sdio_power_on_check: val_mix:0x0000063f, res:0x0000063f
RTW: sdio_power_on_check: 0x100 the result of cmd52 and cmd53 is the same.
RTW: sdio_power_on_check: 0x1B8 test Pass.
RTW: ReadAdapterInfo8723DS, 0x4e=0xc2
RTW: EEPROM type is E-FUSE
RTW: hal_EfuseSwitchToBank: Efuse switch bank to 0
RTW: hal_ReadEFuse_WiFi: data end at address=0x12
RTW: HW EFUSE
RTW: 0x000:
29
81
00
7C
E1
88
07
00
A0
04
EC
35
12
C0
A2
D8
RTW: 0x010:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x020:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x030:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x040:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x050:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x060:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x070:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x080:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x090:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x0a0:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x0b0:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x0c0:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x0d0:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x0e0:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x0f0:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x100:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x110:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x120:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x130:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x140:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x150:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x160:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x170:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x180:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x190:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x1a0:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x1b0:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x1c0:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x1d0:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x1e0:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
RTW: 0x1f0:
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF
FF

RTW: rtw_read_efuse_from_file /system/etc/wifi/wifi_efuse_8723ds.map is not readable
RTW: ERROR invalid phy efuse and read from file fail, will use driver default!!
RTW: rtw_read_macaddr_from_file /data/wifimac.txt is not readable
RTW: [A] 2G G00 CCK-1T base:45 from IC_DEF
RTW: [A] 2G G01 CCK-1T base:45 from IC_DEF
RTW: [A] 2G G02 CCK-1T base:45 from IC_DEF
RTW: [A] 2G G03 CCK-1T base:45 from IC_DEF
RTW: [A] 2G G04 CCK-1T base:45 from IC_DEF
RTW: [A] 2G G05 CCK-1T base:45 from IC_DEF
RTW: [A] 2G G00 BW40-1S base:45 from IC_DEF
RTW: [A] 2G G01 BW40-1S base:45 from IC_DEF
RTW: [A] 2G G02 BW40-1S base:45 from IC_DEF
RTW: [A] 2G G03 BW40-1S base:45 from IC_DEF
RTW: [A] 2G G04 BW40-1S base:45 from IC_DEF
RTW: [B] 2G G00 CCK-1T base:34 from IC_DEF
RTW: [B] 2G G01 CCK-1T base:34 from IC_DEF
RTW: [B] 2G G02 CCK-1T base:34 from IC_DEF
RTW: [B] 2G G03 CCK-1T base:34 from IC_DEF
RTW: [B] 2G G04 CCK-1T base:34 from IC_DEF
RTW: [B] 2G G05 CCK-1T base:34 from IC_DEF
RTW: [B] 2G G00 BW40-1S base:33 from IC_DEF
RTW: [B] 2G G01 BW40-1S base:33 from IC_DEF
RTW: [B] 2G G02 BW40-1S base:33 from IC_DEF
RTW: [B] 2G G03 BW40-1S base:33 from IC_DEF
RTW: [B] 2G G04 BW40-1S base:33 from IC_DEF
RTW: Hal_EfuseParseBTCoexistInfo_8723D: Enable BT-coex, ant_num=1
RTW: hal_com_config_channel_plan use def_chplan:0x20
RTW: Hal_EfuseParseVoltage_8723D hwinfo[EEPROM_Voltage_ADDR_8723D] =a0
RTW: Hal_EfuseParseVoltage_8723D pHalData->adjuseVoltageVal =a
RTW: kfree Pwr Trim flag:1
RTW: bb_gain(S1):-2
RTW: bb_gain(S0):-2
RTW: rtl8723d_FirmwareDownload fw: FW_NIC, size: 27506
RTW: rtl8723d_FirmwareDownload: fw_ver=1b fw_subver=0000 sig=0x23d1, Month=12, Date=07, Hour=14, Minute=07
RTW: rtl8723d_FirmwareDownload(): Shift for fw header!
RTW: rtl8723d_FirmwareDownload by IO write!
RTW: polling_fwdl_chksum: Checksum report OK! (1, 0ms), REG_MCUFWDL:0x07060305
RTW: rtl8723d_FirmwareDownload: download FW count:1
RTW: _8051Reset8723: Finish
RTW: _FWFreeToGo: Polling FW ready OK! (150, 20ms), REG_MCUFWDL:0x070603c6
RTW: rtl8723d_FirmwareDownload success. write_fw:1, 380ms
RTW:  <=== rtl8723d_FirmwareDownload()
RTW: hal_read_mac_hidden_rpt OK! (2, 10ms), fwdl:1, id:0x19
RTW: SetHwReg: bMacPwrCtrlOn=0
RTW: rtw_hal_read_chip_info in 420 ms
RTW: init_mlme_default_rate_set: support CCK
RTW: init_mlme_default_rate_set: support OFDM
RTW: init_channel_set((null)) ChannelPlan ID:0x20, ch num:13
RTW: rtw_alloc_macid((null)) if1, hwaddr:ff:ff:ff:ff:ff:ff macid:1
RTW: Init_ODM_ComInfo_8723d(): fab_ver=0 cut_ver=3
RTW: rtw_regsty_chk_target_tx_power_valid return _FALSE for band:0, path:0, rs:0, t:-1
RTW: phy_ConfigBBWithPgParaFile(): No File PHY_REG_PG.txt, Load from HWImg Array!
RTW: default power by rate loaded
RTW: phy_txpwr_by_rate_chk_for_path_dup duplicate 2.4G [A] to [B]
RTW: ERROR invalid mac addr:00:00:00:00:00:00, assign random MAC
RTW: rtw_macaddr_cfg mac addr:00:e0:4c:18:29:ee
RTW: bDriverStopped:True, bSurpriseRemoved:False, bup:0, hw_init_completed:0
RTW: init_mlme_default_rate_set: support CCK
RTW: init_mlme_default_rate_set: support OFDM
RTW: init_channel_set((null)) ChannelPlan ID:0x20, ch num:13
RTW: rtw_alloc_macid((null)) if2, hwaddr:ff:ff:ff:ff:ff:ff macid:1
RTW: rtw_drv_add_vir_if if2 mac_addr : 02:e0:4c:18:29:ee
RTW: rtw_wiphy_alloc(phy0)
RTW: rtw_wdev_alloc(padapter=(ptrval))
RTW: rtw_wiphy_alloc(phy1)
RTW: rtw_wdev_alloc(padapter=(ptrval))
RTW: rtw_wiphy_register(phy0)
RTW: Register RTW cfg80211 vendor cmd(0x67) interface
RTW: _rtw_reg_notifier
RTW: _rtw_reg_notifier_apply: NL80211_REGDOM_SET_BY_CORE to DRV
RTW: rtw_ndev_init(wlan0) if1 mac_addr=00:e0:4c:18:29:ee
RTW: rtw_ndev_notifier_call(wlan0) state:17
RTW: cfg80211_rtw_get_txpower
RTW: rtw_ndev_notifier_call(wlan0) state:5
RTW: cfg80211_rtw_get_txpower
RTW: rtw_wiphy_register(phy1)
RTW: Register RTW cfg80211 vendor cmd(0x67) interface
RTW: _rtw_reg_notifier
RTW: _rtw_reg_notifier_apply: NL80211_REGDOM_SET_BY_CORE to DRV
RTW: rtw_ndev_init(wlan1) if2 mac_addr=02:e0:4c:18:29:ee
RTW: rtw_ndev_notifier_call(wlan1) state:17
RTW: cfg80211_rtw_get_txpower
RTW: rtw_ndev_notifier_call(wlan1) state:5
RTW: module init ret=0
RTW: cfg80211_rtw_get_txpower
RTW: rtw_ndev_notifier_call(wlan1) state:14
RTW: _netdev_vir_if_open(wlan1) , bup=0
RTW: _netdev_open(wlan0) , bup=0
RTW: FW does not exist before power on!!
RTW: SetHwReg: bMacPwrCtrlOn=1
RTW: sdio_power_on_check: val_mix:0x0000063f, res:0x0000063f
RTW: sdio_power_on_check: 0x100 the result of cmd52 and cmd53 is the same.
RTW: sdio_power_on_check: 0x1B8 test Pass.
RTW: Power on ok!
RTW: rtl8723d_FirmwareDownload fw: FW_NIC, size: 27506
RTW: rtl8723d_FirmwareDownload: fw_ver=1b fw_subver=0000 sig=0x23d1, Month=12, Date=07, Hour=14, Minute=07
RTW: rtl8723d_FirmwareDownload(): Shift for fw header!
RTW: rtl8723d_FirmwareDownload by IO write!
test@localhost:~$ RTW: polling_fwdl_chksum: Checksum report OK! (1, 0ms), REG_MCUFWDL:0x07060705
RTW: rtl8723d_FirmwareDownload: download FW count:1
RTW: _8051Reset8723: Finish
RTW: _FWFreeToGo: Polling FW ready OK! (149, 10ms), REG_MCUFWDL:0x070607c6
RTW: rtl8723d_FirmwareDownload success. write_fw:1, 400ms
RTW:  <=== rtl8723d_FirmwareDownload()
RTW: HalDetectPwrDownMode(): PDN=0
RTW: Set RF Chip ID to RF_6052 and RF type to 3.
RTW: ===>phy_SpurCalibration_8723D: Channel = 1
RTW: ===>phy_SwChnl8723D: Channel = 1
RTW: rtw_hal_set_macaddr_port wlan0- hw port(0) mac_addr =00:e0:4c:18:29:ee
RTW: rtw_hal_set_macaddr_port wlan1- hw port(1) mac_addr =02:e0:4c:18:29:ee
RTW: rtw_hal_get_macaddr_port wlan0- hw port(0) mac_addr =00:e0:4c:18:29:ee
RTW: wlan0- hw port(0) mac_addr =00:e0:4c:18:29:ee
RTW: rtw_hal_get_macaddr_port wlan1- hw port(1) mac_addr =02:e0:4c:18:29:ee
RTW: wlan1- hw port(1) mac_addr =02:e0:4c:18:29:ee
RTW: ===>phy_SpurCalibration_8723D: Channel = 1
RTW: ===>phy_SwChnl8723D: Channel = 1
RTW: rtw_rf_get_kfree_tx_gain_offset path:S1, ch:6, bb_gain_sel:0, kfree_offset:-2
RTW: kfree gain_offset 0x55:0x82010
RTW:  after :0x12010
RTW: rtw_rf_get_kfree_tx_gain_offset path:S0, ch:6, bb_gain_sel:0, kfree_offset:-2
RTW: kfree gain_offset 0x65:0x82000
RTW:  after :0x12000
RTW: MAC Address = 00:e0:4c:18:29:ee
RTW: start rtl8723ds_xmit_thread(wlan0)
RTW: rtw_cfg80211_init_wiphy:rf_type=3
RTW: [HT] HAL Support STBC = 0x01
RTW: _netdev_vir_if_open(wlan1) , bup=0
RTW: rtw_cfg80211_init_wiphy:rf_type=3
RTW: [HT] HAL Support STBC = 0x01
RTW: _netdev_vir_if_open(wlan1) (bup=1) exit
RTW: -871x_drv - drv_open, bup=1
RTW: rtw_cfg80211_init_wiphy:rf_type=3
RTW: [HT] HAL Support STBC = 0x01
RTW: _netdev_vir_if_open(wlan1) (bup=1) exit
RTW: cfg80211_rtw_set_power_mgmt(wlan1) enabled:0, timeout:-1
RTW: rtw_ndev_notifier_call(wlan1) state:1
RTW: cfg80211_rtw_get_txpower
RTW: start rtl8723ds_xmit_thread(wlan1)
RTW: rtw_ndev_notifier_call(wlan0) state:14
RTW: _netdev_open(wlan0) , bup=1
RTW: -871x_drv - drv_open, bup=1
RTW: cfg80211_rtw_set_power_mgmt(wlan0) enabled:0, timeout:-1
RTW: rtw_ndev_notifier_call(wlan0) state:1
RTW: cfg80211_rtw_get_txpower
RTW: cfg80211_rtw_get_txpower
RTW: cfg80211_rtw_get_txpower
RTW: cfg80211_rtw_get_txpower
RTW: cfg80211_rtw_get_txpower
RTW: cfg80211_rtw_get_txpower
RTW: rtw_ndev_notifier_call(wlan1) state:4
RTW: cfg80211_rtw_flush_pmksa(wlan1)
random: crng init done
random: 7 urandom warning(s) missed due to ratelimiting
RTW: cfg80211_rtw_get_txpower
RTW: cfg80211_rtw_get_txpower
RTW: cfg80211_rtw_get_txpower
RTW: cfg80211_rtw_get_txpower
RTW: cfg80211_rtw_get_txpower
RTW: rtw_ndev_notifier_call(wlan0) state:4
RTW: cfg80211_rtw_flush_pmksa(wlan0)
RTW: rtw_ndev_notifier_call(wlan1) state:4
RTW: cfg80211_rtw_scan(wlan1)
RTW: [HW_VAR_CHECK_TXBUF] no packet in tx packet buffer (0)
RTW: ===>phy_SpurCalibration_8723D: Channel = 1
RTW: ===>phy_SwChnl8723D: Channel = 1
RTW: rtw_ndev_notifier_call(wlan0) state:4
RTW: cfg80211_rtw_scan(wlan0)
RTW: ===>phy_SpurCalibration_8723D: Channel = 2
RTW: ===>phy_SwChnl8723D: Channel = 2
RTW: ===>phy_SpurCalibration_8723D: Channel = 3
RTW: ===>phy_SwChnl8723D: Channel = 3
RTW: ===>phy_SpurCalibration_8723D: Channel = 4
RTW: ===>phy_SwChnl8723D: Channel = 4
RTW: ===>phy_SpurCalibration_8723D: Channel = 5
RTW: ===>phy_SwChnl8723D: Channel = 5
RTW: ===>phy_SpurCalibration_8723D: Channel = 6
RTW: ===>phy_SwChnl8723D: Channel = 6
RTW: ===>phy_SpurCalibration_8723D: Channel = 7
RTW: ===>phy_SwChnl8723D: Channel = 7
RTW: ===>phy_SpurCalibration_8723D: Channel = 8
RTW: ===>phy_SwChnl8723D: Channel = 8
RTW: ===>phy_SpurCalibration_8723D: Channel = 9
RTW: ===>phy_SwChnl8723D: Channel = 9
RTW: ===>phy_SpurCalibration_8723D: Channel = 10
RTW: ===>phy_SwChnl8723D: Channel = 10
RTW: ===>phy_SpurCalibration_8723D: Channel = 11
RTW: ===>phy_SwChnl8723D: Channel = 11
RTW: ===>phy_SpurCalibration_8723D: Channel = 12
RTW: ===>phy_SwChnl8723D: Channel = 12
RTW: ===>phy_SpurCalibration_8723D: Channel = 13
RTW: ===>phy_SwChnl8723D: Channel = 13
RTW: ===>phy_SpurCalibration_8723D: Channel = 1
RTW: ===>phy_SwChnl8723D: Channel = 1
RTW: survey done event(1f) band:0 for wlan1
RTW: rtw_indicate_scan_done(wlan1)
RTW: rtw_indicate_scan_done(wlan0)
RTW: cfg80211_rtw_scan(wlan1)
RTW: [HW_VAR_CHECK_TXBUF] no packet in tx packet buffer (0)
RTW: cfg80211_rtw_scan(wlan0)
RTW: ===>phy_SpurCalibration_8723D: Channel = 1
RTW: ===>phy_SwChnl8723D: Channel = 1
RTW: ===>phy_SpurCalibration_8723D: Channel = 2
RTW: ===>phy_SwChnl8723D: Channel = 2
RTW: ===>phy_SpurCalibration_8723D: Channel = 3
RTW: ===>phy_SwChnl8723D: Channel = 3
RTW: ===>phy_SpurCalibration_8723D: Channel = 4
RTW: ===>phy_SwChnl8723D: Channel = 4
RTW: ===>phy_SpurCalibration_8723D: Channel = 5
RTW: ===>phy_SwChnl8723D: Channel = 5
RTW: ===>phy_SpurCalibration_8723D: Channel = 6
RTW: ===>phy_SwChnl8723D: Channel = 6
RTW: ===>phy_SpurCalibration_8723D: Channel = 7
RTW: ===>phy_SwChnl8723D: Channel = 7
RTW: ===>phy_SpurCalibration_8723D: Channel = 8
RTW: ===>phy_SwChnl8723D: Channel = 8
RTW: ===>phy_SpurCalibration_8723D: Channel = 9
RTW: ===>phy_SwChnl8723D: Channel = 9
RTW: ===>phy_SpurCalibration_8723D: Channel = 10
RTW: ===>phy_SwChnl8723D: Channel = 10
RTW: ===>phy_SpurCalibration_8723D: Channel = 11
RTW: ===>phy_SwChnl8723D: Channel = 11
RTW: ===>phy_SpurCalibration_8723D: Channel = 12
RTW: ===>phy_SwChnl8723D: Channel = 12
RTW: ===>phy_SpurCalibration_8723D: Channel = 13
RTW: ===>phy_SwChnl8723D: Channel = 13
RTW: ===>phy_SpurCalibration_8723D: Channel = 1
RTW: ===>phy_SwChnl8723D: Channel = 1
RTW: survey done event(1f) band:0 for wlan1
RTW: rtw_indicate_scan_done(wlan1)
RTW: rtw_indicate_scan_done(wlan0)

test@localhost:~$ sudo nmcli c
NAME         UUID                                  TYPE  DEVICE
XXXXX  XXXXXXXXXXXXXXXX  wifi  --
test@localhost:~$ sudo nmcli c del XXXXXXXXXXXXXXXX
Connection XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX successfully deleted.
test@localhost:~$ sudo nmcli RTW: cfg80211_rtw_scan(wlan1)
RTW: cfg80211_rtw_scan(wlan0)
RTW: [HW_VAR_CHECK_TXBUF] no packet in tx packet buffer (0)
RTW: ===>phy_SpurCalibration_8723D: Channel = 1
RTW: ===>phy_SwChnl8723D: Channel = 1
RTW: ===>phy_SpurCalibration_8723D: Channel = 2
RTW: ===>phy_SwChnl8723D: Channel = 2
RTW: ===>phy_SpurCalibration_8723D: Channel = 3
RTW: ===>phy_SwChnl8723D: Channel = 3
RTW: ===>phy_SpurCalibration_8723D: Channel = 4
RTW: ===>phy_SwChnl8723D: Channel = 4
RTW: ===>phy_SpurCalibration_8723D: Channel = 5
RTW: ===>phy_SwChnl8723D: Channel = 5
RTW: ===>phy_SpurCalibration_8723D: Channel = 6
RTW: ===>phy_SwChnl8723D: Channel = 6
RTW: ===>phy_SpurCalibration_8723D: Channel = 7
RTW: ===>phy_SwChnl8723D: Channel = 7
RTW: ===>phy_SpurCalibration_8723D: Channel = 8
RTW: ===>phy_SwChnl8723D: Channel = 8
RTW: ===>phy_SpurCalibration_8723D: Channel = 9
RTW: ===>phy_SwChnl8723D: Channel = 9
RTW: ===>phy_SpurCalibration_8723D: Channel = 10
RTW: ===>phy_SwChnl8723D: Channel = 10
RTW: ===>phy_SpurCalibration_8723D: Channel = 11
RTW: ===>phy_SwChnl8723D: Channel = 11
RTW: ===>phy_SpurCalibration_8723D: Channel = 12
RTW: ===>phy_SwChnl8723D: Channel = 12
RTW: ===>phy_SpurCalibration_8723D: Channel = 13
RTW: ===>phy_SwChnl8723D: Channel = 13
RTW: ===>phy_SpurCalibration_8723D: Channel = 1
RTW: ===>phy_SwChnl8723D: Channel = 1
RTW: survey done event(27) band:0 for wlan1
RTW: rtw_indicate_scan_done(wlan1)
RTW: rtw_indicate_scan_done(wlan0)

wlan0: disconnected
        "wlan0"
        wifi (rtl8723ds), 00:E0:4C:18:29:EE, hw, mtu 1500

wlan1: disconnected
        "wlan1"
        wifi (rtl8723ds), 02:E0:4C:18:29:EE, hw, mtu 1500

sit0: unmanaged
        "sit0"
        iptunnel (sit), sw, mtu 1480

lo: unmanaged
        "lo"
        loopback (unknown), 00:00:00:00:00:00, sw, mtu 65536

Use "nmcli device show" to get complete information about known devices and
"nmcli connection show" to get an overview on active connection profiles.

Consult nmcli(1) and nmcli-examples(5) manual pages for complete usage details.
test@localhost:~$ sudo nmcli dev wifi list
IN-USE  SSID                         MODE   CHAN  RATE        SIGNAL  BARS  SECU
RITY
        --                           Infra  7
270 Mbit/s  39      ▂▄__  WPA2
        --                           Infra  1
130 Mbit/s  37      ▂▄__  WPA2

test@localhost:~$ sudo nmcli dev wifi conneRTW: cfg80211_rtw_scan(wlan1)
RTW: cfg80211_rtw_scan(wlan0)
RTW: [HW_VAR_CHECK_TXBUF] no packet in tx packet buffer (0)
RTW: ===>phy_SpurCalibration_8723D: Channel = 1
RTW: ===>phy_SwChnl8723D: Channel = 1
cRTW: ===>phy_SpurCalibration_8723D: Channel = 2
RTW: ===>phy_SwChnl8723D: Channel = 2
RTW: ===>phy_SpurCalibration_8723D: Channel = 3
RTW: ===>phy_SwChnl8723D: Channel = 3
tRTW: ===>phy_SpurCalibration_8723D: Channel = 4
RTW: ===>phy_SwChnl8723D: Channel = 4
RTW: ===>phy_SpurCalibration_8723D: Channel = 5
RTW: ===>phy_SwChnl8723D: Channel = 5
RTW: ===>phy_SpurCalibration_8723D: Channel = 6
RTW: ===>phy_SwChnl8723D: Channel = 6
RTW: ===>phy_SpurCalibration_8723D: Channel = 7
RTW: ===>phy_SwChnl8723D: Channel = 7
RTW: ===>phy_SpurCalibration_8723D: Channel = 8
RTW: ===>phy_SwChnl8723D: Channel = 8
RTW: ===>phy_SpurCalibration_8723D: Channel = 9
RTW: ===>phy_SwChnl8723D: Channel = 9
RTW: ===>phy_SpurCalibration_8723D: Channel = 10
RTW: ===>phy_SwChnl8723D: Channel = 10
RTW: ===>phy_SpurCalibration_8723D: Channel = 11
RTW: ===>phy_SwChnl8723D: Channel = 11
RTW: ===>phy_SpurCalibration_8723D: Channel = 12
RTW: ===>phy_SwChnl8723D: Channel = 12
RTW: ===>phy_SpurCalibration_8723D: Channel = 13
RTW: ===>phy_SwChnl8723D: Channel = 13
RTW: ===>phy_SpurCalibration_8723D: Channel = 1
RTW: ===>phy_SwChnl8723D: Channel = 1
RTW: survey done event(21) band:0 for wlan1
RTW: rtw_indicate_scan_done(wlan1)
RTW: rtw_indicate_scan_done(wlan0)

Error: SSID or BSSID are missing.
test@localhost:~$ sudo nmcli dev wifi connect XXXXXXXXXXXX password XXXXXXXXXXXXXXX
RTW: cfg80211_rtw_set_power_mgmt(wlan0) enabled:1, timeout:-1
RTW: cfg80211_rtw_scan(wlan0)
RTW: rtw_cfg80211_set_probe_req_wpsp2pie(wlan0) listen channel - country:XX, class:81, ch:1
RTW: [HW_VAR_CHECK_TXBUF] no packet in tx packet buffer (0)
RTW: ===>phy_SpurCalibration_8723D: Channel = 1
RTW: ===>phy_SwChnl8723D: Channel = 1
RTW: ===>phy_SpurCalibration_8723D: Channel = 2
RTW: ===>phy_SwChnl8723D: Channel = 2

`

**Comment by lwfinger** [comment]
Stop using this repo and switch to https://github.com/lwfinger/rtw88.git. There is a much more reliable driver for rtl8723ds in rtw88.

**Comment by briansune** [comment]
@lwfinger 

I had tried the RTW88 but it is not working, once the driver is insert the WLAN0 is also shown but there are no response on any WIFI scan or connect.

**Comment by lwfinger** [comment]
Reboot without inserting the module, and post the output of 'lsmod | grep rtw'. It is possible that your device is not being recognized. In addition, is the firmware installed? Check 'ls /lib/firmware/rtw88/' for rtw8723d_fw.bin.xz or rtw8723d_fw.bin.

**Comment by briansune** [comment]
@lwfinger 

For lib/firmware/rtw88/
I am 1E+Googleplex% sure it is there and I also tried replace exist one with the repository one.
![image](https://github.com/lwfinger/rtl8723ds/assets/29487339/d3585bf9-a0f0-41c2-b436-4eee9d2d534f)
![image](https://github.com/lwfinger/rtl8723ds/assets/29487339/57e80c97-88b2-42a4-b867-12345f57691c)

**Comment by briansune** [comment]
Maybe could you guide me how to enable more debug message to debug on both side?
I am not sure what should I modify.

Thank you

**Comment by lwfinger** [comment]
Run the command 'sudo dmesg > dmesg.txt' and attach dmesg.txt to this issue.

**Comment by briansune** [comment]
@lwfinger 

No I am referring to RTW drivers itself.
For example, if I use the other  RTL8723DS driver repository I can modify the debug level to 4 and see all the driver load info.
However for the RTW I have no clue where to start.

Thank you

**Comment by lwfinger** [comment]
One thing I see is that your system does not have CRDA installed. That shows up with
[    1.243518] cfg80211: failed to load regulatory.db

I see nothing after module loading other than the firmware was loaded.  Normally, I would expect
[    6.480426] rtw89_8852be 0000:02:00.0: loaded firmware rtw89/rtw8852b_fw-1.bin
[    6.515080] rtw89_8852be 0000:02:00.0: Firmware version 0.29.29.1, cmd version 0, type 5
[    6.854445] rtw89_8852be 0000:02:00.0 wls1: renamed from wlan0

 What user-space code are you using to control wifi?

To get the kind of debugging that you want, set to load rtw_core with option debug_mask=mask, where the mask has bits as follows:
debug.h:        RTW_DBG_PCI             = 0x00000001,
debug.h:        RTW_DBG_TX              = 0x00000002,
debug.h:        RTW_DBG_RX              = 0x00000004,
debug.h:        RTW_DBG_PHY             = 0x00000008,
debug.h:        RTW_DBG_FW              = 0x00000010,
debug.h:        RTW_DBG_EFUSE           = 0x00000020,
debug.h:        RTW_DBG_COEX            = 0x00000040,
debug.h:        RTW_DBG_RFK             = 0x00000080,
debug.h:        RTW_DBG_REGD            = 0x00000100,
debug.h:        RTW_DBG_DEBUGFS         = 0x00000200,
debug.h:        RTW_DBG_PS              = 0x00000400,
debug.h:        RTW_DBG_BF              = 0x00000800,
debug.h:        RTW_DBG_WOW             = 0x00001000,
debug.h:        RTW_DBG_CFO             = 0x00002000,
debug.h:        RTW_DBG_PATH_DIV        = 0x00004000,
debug.h:        RTW_DBG_ADAPTIVITY      = 0x00008000,
debug.h:        RTW_DBG_HW_SCAN         = 0x00010000,
debug.h:        RTW_DBG_STATE           = 0x00020000,
debug.h:        RTW_DBG_SDIO            = 0x00040000,
debug.h:        RTW_DBG_ALL             = 0xffffffff

you probably do not want to start with 0xffffffff. Perhape 0x4000e to get SDIO, TX, RX and PHY.

**Comment by briansune** [comment]
@lwfinger 

This is a kernel boot and the driver is undergo a module not CFG_XXXX=y but CFG_XXXX=m.

**Comment by briansune** [comment]
@lwfinger 

I am a bit lost about set to load rtw_core with option debug_mask=mask

Do you mean insmod with this flag or compile using flag?
Thank you

**Comment by lwfinger** [comment]
It is not a compile-time flag. The insmod will work, or you can create a file in /usr/lib/modprobe.d/ to load the option every time the module is loaded. Create /usr/lib/modprobe.d/70-rtwcore.conf and add one line that says
options rtw_core debug_mask=<mask that you want>

**Comment by briansune** [comment]
@lwfinger 

I might be wrong why file 70-rtwcore.conf ?
The file name should aligned with?

Thank you

**Comment by briansune** [comment]
@lwfinger 

Okay, ignore the file stuff:


![image](https://github.com/lwfinger/rtl8723ds/assets/29487339/dbbd1955-b782-47dd-b330-57c1d016f88e)

**Comment by lwfinger** [comment]
Yes, the file name does not matter. It looks as if your kernel is compiled without SDIO debugging. Change the mask to 0xe.

**Comment by briansune** [comment]
![image](https://github.com/lwfinger/rtl8723ds/assets/29487339/ad3ee449-94b8-4a8e-8609-9debb0146bec)

**Comment by briansune** [comment]
@lwfinger 

How can I activate the necessary SDIO debugging and other debugging flags?

Thank you

**Comment by briansune** [comment]
Let me make sure I am doing the correct stuff (NOT really a Linux engineer at all).

I run the following commnad:

> sudo insmod rtw_core.ko debug_mask=0xe
> sudo insmod rtw_sdio.ko
> sudo insmod rtw_8723d.ko
> sudo insmod rtw_8723ds.ko

dmesg

> sudo insmod rtw_core.ko debug_mask=0x00040000
> sudo insmod rtw_sdio.ko
> sudo insmod rtw_8723d.ko
> sudo insmod rtw_8723ds.ko

dmesg
![image](https://github.com/lwfinger/rtl8723ds/assets/29487339/3697c5cb-1a1b-4de2-ae18-6d9f9753613b)

**Comment by briansune** [comment]
@lwfinger 

If I use all mask:
![image](https://github.com/lwfinger/rtl8723ds/assets/29487339/622aa3d1-294f-4834-82b3-b48166a67348)

**Comment by lwfinger** [comment]
Yiou can do the insmod calls in that order, or you can do a 'sudo make install', then 'sudo modprobe -v rtw8723ds'.

**Comment by briansune** [comment]
[dmesg.txt](https://github.com/lwfinger/rtl8723ds/files/12178202/dmesg.txt)

**Comment by briansune** [comment]
@lwfinger 

here a dmesg.txt

**Comment by lwfinger** [comment]
I do not see anything wrong. Remember that I asked you earliier about what user-space software you are using? I did not see an answer from you.

**Comment by briansune** [comment]
What do you mean  user-space software.

**Comment by briansune** [comment]
@lwfinger 

Maybe I make this more clear.
I used the same system on both repositories.
The old one is able to ping IP in short period before crashes.
And the the latest one is not able to list wifi via
> nmcli dev wifi list

**Comment by lwfinger** [comment]
OK, using nmcli means you are using NetworkManager as your user-space software. Are you running a GUI desktop? Can you install the full NetworkManager?

I posted your debug information on linux-wireless and asked if the experts see anything that I do not.

**Comment by briansune** [comment]
@lwfinger 

I already told you this is like a raspberry pi system no ethernet bare-bone and no GUI at all only serial port communication.

**Comment by briansune** [comment]
@lwfinger 

What do you mean  full NetworkManager?
I know very little on these stuff.
I just know simple compile and modifications.
Any could it possible to debug like the old driver shown the RTL8723DS is loaded and the efuse or map is reload?
Just make sure the bottom layer is working properly of cause  you may argue that if the old driver is functioning that the new one should do so.
But never be sure enough right?

Thank  you

**Comment by lwfinger** [comment]
I am never going to debug the vendor driver. If you want to, be my guest.

**Comment by briansune** [comment]
@lwfinger 

My meaning is that do the rtw88 also provide same debug level as the previous driver repository does?
I think they both share some similarity?

**Comment by lwfinger** [comment]
What is your machine with the rtl8723ds?

**Comment by briansune** [comment]
@lwfinger 

As mentioned again this is like raspberry pi ARM-based system.

**Comment by lwfinger** [comment]
I want to know exactly what it is, not what it is like. If it is not too expensive, I might buy one.

**Comment by briansune** [comment]
@lwfinger 

I don't think you could buy, this is custom design board with NDA.
I am happy to hear you would give it a try but not an option

**Comment by briansune** [comment]
@lwfinger 

I have another test just finish.

Result as follows:
If I use the same repository of RTW88.
The USB based RLT8723du [D] NOT [B].
It seems like no crash and pinging is normal, no reboot.

I am not sure is it the SDIO is not stable?

Thank you

**Comment by briansune** [comment]
@lwfinger 

For SDIO RTL8723DS, I observed that the LDO of the chip only giving 0.8V.
While old driver repository is 1.25V as normal.
Is there any wrongly configured registers?

Thank you

**Comment by lwfinger** [comment]
The SDIO driver is new, the USB driver is slightly older, and the PCI driver was written earliest. It is fair to say that the number of bugs is inversely related to the age of the driver.

Your question about LDO is beyond my expertise. I am not a hardware guy, and not even sure what the abbreviation means, but that certainly looks like a problem. You need to post that question on linux-wireless@vger.kernel.org. Be as complete as you can about the description of the system. In particular, what SDIO controller chip is being used. If you write a good enough description about the problem, you might get one of the SDIO experts interested. If not, your E-mail will be ignored.

**Comment by lwfinger** [comment]
I did find a couple of placed that look interesting. In file rtw8723d.c is hte routine below:

static void rtw8723d_cfg_ldo25(struct rtw_dev *rtwdev, bool enable)
{       
        u8 ldo_pwr;
        
        ldo_pwr = rtw_read8(rtwdev, REG_LDO_EFUSE_CTRL + 3);
        if (enable) {           
                ldo_pwr &= ~BIT_MASK_LDO25_VOLTAGE;
                ldo_pwr |= (BIT_LDO25_VOLTAGE_V25 << 4) | BIT_LDO25_EN;
        } else {
                ldo_pwr &= ~BIT_LDO25_EN;
        }
        rtw_write8(rtwdev, REG_LDO_EFUSE_CTRL + 3, ldo_pwr);
}       
        
It is called from file efuse.c in the following location:

static int rtw_dump_physical_efuse_map(struct rtw_dev *rtwdev, u8 *map)
{
        const struct rtw_chip_info *chip = rtwdev->chip;
        u32 size = rtwdev->efuse.physical_size;
        u32 efuse_ctl;
        u32 addr;
        u32 cnt;

        rtw_chip_efuse_grant_on(rtwdev);
        
        switch_efuse_bank(rtwdev);

        /* disable 2.5V LDO */
        chip->ops->cfg_ldo25(rtwdev, false);

        efuse_ctl = rtw_read32(rtwdev, REG_EFUSE_CTRL);

It might be worthwhile adding some test prints in those locations.

**Comment by lwfinger** [comment]
In the vendor driver, file core/efuse/rtw_efuse.c has the following:

        readbyte = rtw_read8(Adapter, EFUSE_CTRL + 2);
        rtw_write8(Adapter, EFUSE_CTRL + 2, ((_offset >> 8) & 0x03) | (readbyte & 0xfc));

        /* Write bit 32 0 */
        readbyte = rtw_read8(Adapter, EFUSE_CTRL + 3);
        rtw_write8(Adapter, EFUSE_CTRL + 3, (readbyte & 0x7f));

I have not yet had time to see what the 2 codes are doing differently. I will work on it them I get time.

**Comment by briansune** [comment]
@lwfinger 

Really apricate the insight of pointing out specific code.
LDO means the internal voltage regulator.
According to the chip specification the chip need at least 1.25V or above to work properly.
I can be switch or internal regulator luckily I am more hardware engineer.

However, I am no driver engineer.

I will see the different and give it a try.
Most likely is all about efuse settings.

Thank you

**Comment by briansune** [comment]
@lwfinger 

I found that there are lines of code compare old vs new is missing:
![image](https://github.com/lwfinger/rtl8723ds/assets/29487339/ff72ef46-7fab-4525-88fe-cc4a3e7a1752)

I am not sure how to correct accordingly.

**Comment by briansune** [comment]
@lwfinger 

I might be wrong:
According to my little software knowledge:
I guess the below code is aligned.
(Left is new driver, Right is old driver)

![image](https://github.com/lwfinger/rtl8723ds/assets/29487339/60ff26f9-ae32-4e8c-a531-ab5be77fd1a3)

But I am not sure above the setup:
![image](https://github.com/lwfinger/rtl8723ds/assets/29487339/fb1f9e6e-1aa8-4c95-9b51-0b3e633b748f)

And I cannot found the old driver code from new one:
![image](https://github.com/lwfinger/rtl8723ds/assets/29487339/45e06185-1162-4448-bac0-aba8708236ce)

This also raise to one question if the efuse of the chip is lost that will it loaded a default one?

**Comment by briansune** [comment]
@lwfinger 

Meanwhile,

I believe there should be some issue on the crystal when efuse is missing:
![image](https://github.com/lwfinger/rtl8723ds/assets/29487339/7a57fa6d-4253-4603-89a3-ccfbf46b9d10)

When load failed it should enters a auto load routing that configure the efuse setting as default.
So this is possible root case that make such regulation output.

I hope this could help.
My knowledge really ends here.
Can't do even much (no clue)

**Comment by lwfinger** [comment]
Your images are really hard to see. When you find a difference, please send me a file name and line number. My eyes are not that good.

I did an analysis of the code for  rtw8723d.c which does, and removed some of the macros:
static void rtw8723d_cfg_ldo25(struct rtw_dev *rtwdev, bool enable)
{
        u8 ldo_pwr;

        ldo_pwr = rtw_read8(rtwdev, 0x37);
        if (enable) {
                ldo_pwr &= ~70;    /* == 0x8f */
                ldo_pwr |= (0x3 << 4) | 0x80;
        } else {
                ldo_pwr &= ~0x80;
        }
        rtw_write8(rtwdev, 0x37, ldo_pwr);
}

The equivalent part of the vendor code does:
                if (bWrite == _TRUE) {
                        /* Enable LDO 2.5V before read/write action */
                        tempval = rtw_read8(padapter, 0x37);
                        tempval &= 0x0F;
                        tempval |= (0x03 << 4) | 0x80;
                        rtw_write8(padapter, 0x37, tempval);
                } else {
                        tempval = rtw_read8(padapter, 0x37);
                        rtw_write8(padapter, 0x37, (tempval & 0x7F));
                }

At first glance, they look different, but that difference in the mask of the readout will be overwritten by the OR operation with 0x80 for the writes and that bit is cleared when done. This code is OK.

There is a utility that allows logging all the traffic to/from a particular USB device, but I could not find one for SDIO.

I added a test branch to both rtw88 and the vendor driver. Please do a 'git checkout origin/test -b test' and a 'git pull' in each directory. Build and run each for a minute, or so, make "dmesg.txt" for each driver, and attach the file here.

**Comment by briansune** [comment]
@lwfinger 

I will give it a try.
Meanwhile I think the image can click and enlarge to real size (unless it is compressed).
Of cause line and file is more easy to follow.

Thanks again for helping out.

**Comment by briansune** [comment]
@lwfinger 

Here is the new test repository dmesg:
[dmesg.txt](https://github.com/lwfinger/rtl8723ds/files/12208041/dmesg.txt)

**Comment by briansune** [comment]
@lwfinger 

The LDO output now is 1.22xV so it is still lower than expected.
According to previous measurement the LDO in old repository should raise after driver is inserted.
So the voltage should go from 1.22 to 1.26.

Bests,
Brian

**Comment by briansune** [comment]
@lwfinger 

For both test and default driver in RTL88 SDIO RTL8723DS case.

wlan0: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether ff:ff:ff:ff:ff:ff  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

sudo ifconfig wlan0 up
SIOCSIFFLAGS: Cannot assign requested address

So the WLAN0 is not functioning.

**Comment by lwfinger** [comment]
All I did was add some debugging. I did not expect a change in the behavior.

Where is the dmesg for the test version of rtl8723ds - the vendor driver. The whole reason for this exercise is to see what is written differently between rtw88 and the vendor driver.

**Comment by briansune** [comment]
oops, you also made a test repository on the old rtl8723DS driver.
I had not notice.
Hold on and give u a dmesg.txt

**Comment by briansune** [comment]
@lwfinger 

Here you g
[dmesg.txt](https://github.com/lwfinger/rtl8723ds/files/12208340/dmesg.txt)
o this is the old repository of RTL8723DS dmesg.

**Comment by lwfinger** [comment]
I just pushed commits for both drivers. The rtw88 one will let me know if the efuse is being read.

Please but and run each of them and attach their dmesg output.

**Comment by briansune** [comment]
@lwfinger 

I am working out that two updated repository:

Meanwhile, I discover there is a warning keep posting in the old repository RTL8723DS driver.
This is the only message shown during built.

div64.h:226:28: warning: comparison of distinct pointer types lacks a cast
  226 |  (void)(((typeof((n)) *)0) == ((uint64_t *)0)); \
      |                            ^~
rtl8723ds/os_dep/linux/ioctl_cfg80211.c:345:9: note: in expansion of macro 'do_div'
  345 |  return do_div(ts, 1000);

**Comment by briansune** [comment]
@lwfinger 

For old repository test pull:
[dmesg_old_driver.txt](https://github.com/lwfinger/rtl8723ds/files/12223522/dmesg_old_driver.txt)

For new RTW88 test pull:
[dmesg_new_driver.txt](https://github.com/lwfinger/rtl8723ds/files/12223534/dmesg_new_driver.txt)


Thank you

**Comment by lwfinger** [comment]
For rtw88, I do not think the EFUSE is being read properly. The line at
[   78.675776] ****** rtw88: efuse->addr ff:ff:ff:ff:ff:ff
shows that. 

I just pushed a fix to the master and test branches of the c=vendor driver to fix that warning, which really was a bug. It might fix your crashes with that driver.

**Comment by briansune** [comment]
@lwfinger 

Really thank you for such work.
With my little programming guess I think it could make a null pointer case?
I might be very wrong =S

As for the the RTW88 EFUSE I also discover that my chip is not loaded with default EFUSE value so it needs a extra efuse map loading or reload via the interface.

So I guess this also make it prefect candidate to debug both drivers.

Again appreciate all the works.

BIG BIG THUMBS UP

**Comment by briansune** [comment]
@lwfinger 

Nope,  for the old driver it works a bit longer but after a while it is just repeating the same behavior.
No luck.
Meanwhile during compile the warning message still showing up:

include/asm-generic/div64.h:226:28: warning: comparison of distinct pointer types lacks a cast
  226 |  (void)(((typeof((n)) *)0) == ((uint64_t *)0)); \

rtl8723ds/os_dep/linux/ioctl_cfg80211.c:345:2: note: in expansion of macro 'do_div'
  345 |  do_div(ts, (uint32_t)1000);

**Comment by briansune** [comment]
@lwfinger 

I think even the EFUSE is read, there are case chip is not fused with default EFUSE setting.
If so the do the RTW88 load a default fuse setting like the RTL8723DS old driver?


> 

RTW: rtw_read_efuse_from_file /system/etc/wifi/wifi_efuse_8723ds.map is not readable
RTW: ERROR invalid phy efuse and read from file fail, will use driver default!!
RTW: rtw_read_macaddr_from_file /data/wifimac.txt is not readable

**Comment by lwfinger** [comment]
I have one more thing to try to get the crash report. After you boot with the vendor driver installed, make the wifi connection, and add an "&" after your ping so that it runs in the background. Then run 'sudo dmesg -wt'. If you get anything about the crash when the system dies, post it here.

I will need to look into providing a backup EFUSE.

**Comment by briansune** [comment]
@lwfinger 

Here is the result:
[dmesg_old_ping.txt](https://github.com/lwfinger/rtl8723ds/files/12246351/dmesg_old_ping.txt)

**Comment by lwfinger** [comment]
Unfortunately, the system is not telling us why it is rebooting.

**Comment by briansune** [comment]
@lwfinger 

That is why I am also frustrated.
This is like a bootarg miswrite and it completely stuck with no further info giving.

**Comment by briansune** [comment]
@lwfinger 

Any update on this issue?

Thank you

**Comment by lwfinger** [comment]
None. You cannot provide the info regarding the spontaneous reboot, and I have no clue as to why rtw88 fails.

BTW, that measurement of LDO is meaningless. It should be 2.5 V ONLY when EFUSE is being written. Yours has never been completely written. Bytes 0x10 to 0x20 should contain the power settings, but yours has only 0x12 bytes written.

Something is screwy about your hardware!

**Comment by briansune** [comment]
@lwfinger 

I can only provide what it happens and it is truly reboot with no return message or even stuck with no further message return.

As for LDO, this is incorrect that the chip uses 1.25V not 2.5V. If 2.5V is given it will fire the chip core immediately.
You can read the datasheet from here as reference.
I am more a hardware guy so under my experience the inherent case for 0.8V is 100% faulty but 1.23 should able to get st out.

But as I mentioned after you patch the LDO or DCDC had gone to 1.24V but no WIFI scan is create.
So I highly suspect it is a crystal issue. The crystal can accept 24,25,26,40 etc.

I attach a datasheet for reference.

https://mangopi.org/_media/rtl8723ds-cg_datasheet_0.92_20170804.pdf

**Comment by briansune** [comment]
@lwfinger 

Also as I had observed again.
There are vendor with EFUSE preloaded and EFUSE free chip.
So when EFUSE is not preloaded it will use map file as first loading.
When both is not found it will load a default from the driver.
This is what I also observed from the old driver aka vendor as you labeled.

I will try to re-spin a new board and compare the result but RTW88 could highly missing a default EFUSE loading method.
Keep in posted

**Comment by briansune** [comment]
@lwfinger 

I got a good news:
For old driver, we finial get it stable for over hour and still running strong.
Our suspected cause is the power supply rails are too dirty.
We added couples of filter and beads.

As for the new rtw88 it is still problematic that it cannot scan or get the wlan0 up.

Thank you

**Comment by lwfinger** [comment]
That is good news. Too much ripple on the power input lines can cause all kinds of problems. A few capacitors and inductors can work wonders. Yes, I used to do design work back in the SSI times (1970's).

I am looking into creating a config file containing the EFUSE information.

**Comment by briansune** [comment]
@lwfinger 

This is pain in the ass. We suspect the noise is injected from the SDIO interface.
And with the RTL8723 DCDC rather than LDO this eventually adds up to a point of fail.

Great to hear there would be an efuse updates.

Thank you

**Comment by briansune** [comment]
@lwfinger 

We are delightful to the rtw88 driver update.
Any good news from that?

Thank you

**Comment by lwfinger** [comment]
I took delivery of an RTL8723DE today. From that, I will get a valid EFUSE image to be added whenever the actual device was not programmed. I have no idea how soon that will be available.

**Comment by briansune** [comment]
@lwfinger 

Understood and really appreciate all the works.
Meanwhile, I think direct purchase new chip is generally not fused.
So this is why REALTEK mostly work with broker or direct company.
And all documents are so limited to a point for developers are pain as hell.

After my verification of both BT and WIFI I will conduct the last stage of WIFI AT + STA.
I think the old driver do able to run on both mode as the same time?
So RTL8723DS can coexist with BT WIFI (AP + STA) if I understand correctly?

Thank you

**Comment by briansune** [comment]
@lwfinger 

Experiment is completed. Turns out it is named as concurrent mode (whatever it calls).
So AP+STA can be coexist and also bluetooth can join to 8723.
This is so power chip, but UART is still unstable.

Once I reboot the system the attach no longer works.
It must undergo power cycle.
Do you have any idea to fix such issue?

Thank you

**Comment by briansune** [comment]
@lwfinger 

I am not using flow hardware control because I am not sure why it is not working.
It might be the DTSI setting is wrong.
So for no hardware flow setup I will try pull the RTS pin as the datasheet required.
But I don't think this is the major cause or not even related.

The reasons are as follow:
1) cool boot do not introduce such issue frequently.
2) sudo reboot and after boot the attach command is 100% repeatable and no longer attachable the UART BT.
3) This can be resolve via power off and power on cycling

Thank you

**Comment by briansune** [comment]
@lwfinger 

After several experiments, it is sure that the UART driver can only insert ONCE and only ONCE.
If insertion is happened and reboot the insmod and rtk_hciattach will not work any more:


sudo ./rtk_hciattach -s 115200 /dev/ttyPS1 rtk_h5
Realtek Bluetooth :Realtek Bluetooth init uart with init speed:115200, type:HCI UART H5
Realtek Bluetooth :Realtek hciattach version 3.1.8905594.20200602-140152

Realtek Bluetooth :Use epoll
Realtek Bluetooth WARN: OP_H5_SYNC Transmission timeout
Realtek Bluetooth WARN: OP_H5_SYNC Transmission timeout
Realtek Bluetooth WARN: OP_H5_SYNC Transmission timeout
Realtek Bluetooth WARN: OP_H5_SYNC Transmission timeout
Realtek Bluetooth WARN: OP_H5_SYNC Transmission timeout
Realtek Bluetooth WARN: OP_H5_SYNC Transmission timeout
Realtek Bluetooth WARN: OP_H5_SYNC Transmission timeout
Realtek Bluetooth WARN: OP_H5_SYNC Transmission timeout
Realtek Bluetooth WARN: OP_H5_SYNC Transmission timeout
Realtek Bluetooth WARN: OP_H5_SYNC Transmission timeout
Realtek Bluetooth WARN: OP_H5_SYNC Transmission timeout
Realtek Bluetooth ERROR: Retransmission exhausts


@lwfinger 
Do you have any idea how to resolve such issue or in your experience what BT code involving a reset?

Thank you

**Comment by lwfinger** [comment]
"After several experiments, it is sure that the UART driver can only insert ONCE and only ONCE.
If insertion is happened and reboot the insmod and rtk_hciattach will not work any more:"

That make no sense! After a cold boot, the UART driver will be loaded. What you are seeing is that it is loaded BEFORE the system is ready, probably because the voltages have not settled. You need to blacklist the driver, and prepare a start-up script that delays for 5 or 10 sec, and then loads the driver.

**Comment by briansune** [comment]
@lwfinger 

The driver is a module .ko and will not load unless manually enter CMD
> sudo insmod hci_uart.ko

That's why I mentioned after inserting the driver and run all bluetooth tests.
sudo reboot and try to attach again it will not work any more.

I hope this can make sure the situation is understand correctly.

**Comment by briansune** [comment]
@lwfinger 

The all RTL8723DS.ko and HIC_UART.ko driver WILL NOT insert automatically.
Because the /lib/module/xxx modprobe is not what we are using.
I do understand normal method or CPU using such method, but we are not allowing auto insert and the kernel driver will only load what CFG_XXXX=y rather than CFG_xxxx=m

**Comment by briansune** [comment]
@lwfinger 

Or I make another example that could even more clear.
Ignore the reboot halt or cold-boot.

If I run the follow command first time
> sudo ./rtk_hciattach -s 115200 /dev/ttyPS1 rtk_h5 

All things are good and working.
What if I
> ps -a
> kill ID rtk_hciattach 

And run again
> sudo ./rtk_hciattach -s 115200 /dev/ttyPS1 rtk_h5

All things no longer working =[
So I don't think this is about power-timing.

Thank you

**Comment by lwfinger** [comment]
You did not explain things very clearly. Obviously rtk_hciattach does not clean things up when it exits. Until that is fixed, you will need to reboot whenever it needs to be reloaded.

**Comment by briansune** [comment]
@lwfinger 

But reboot without power cycling also not working. This is why I mentioned the above situations.
So as you had pointed out, this is highly suspected to clear when reload or exit.

Thank you

**Comment by briansune** [comment]
@lwfinger 

I might asking too much but I see there is a repository that about RTL8723BS_BT.
And I had tried that and the last bit of initialization is not working.
Would it possible to guide which part need to modify to support RTL8723DS?

Thank you

**Comment by lwfinger** [comment]
It is the power off that is critical, not the reboot. The code is leaving the UART is an unrecoverable state. rtk_hciattach is the problem, but I will not be the one that fixes it.

If you had some way to power down the BT part of RTL8723DS, that should work without a reboot.

**Comment by briansune** [comment]
@lwfinger 

Do you mean the pin of BT_DIS#

> Shared with GPIO11. This pin can externally shut down the RTL8723DS
BT function when BT_DIS# is pulled Low. When this pin is pulled low, uart
interface will be also disabled.
This pin can be also defined asthe BT Radio-off function with host interface
remaining connected.

So the dtsi also need a define properly from start to make the diver work properly.
But do there any software flag that could make this happen?

@lwfinger 
I understand you are not going to modify and make this work.
This is why I would like to learn more and have a bit more guide to make this happen.

@lwfinger 
Also do the reboot you are referring means power-cycling?
Because command
> sudo reboot
Do not resolve the issue but a power off power on will make it work again.

Thank you

**Comment by briansune** [comment]
@lwfinger 

Long story short.
I had used some mod-wire  attach a simple push switch and kill the rtk_hciattach.
And after the sudo kill PID.

>Bluetooth: HCI_RUNNING is not cleared before.
light3d@localhost:~$ Bluetooth: hci0: sending frame failed (-49)

And I press the switch from H->L
And reattach
> rtk_hciattach -s ....

And all it normal.

@lwfinger 
Good insight that BT UART could enters are unrecoverable state.
So the pin of
BT_DIS# I 43
actually is a must connect incase software is buggy.

@lwfinger 
Do this mean the software is not able to reset the interface and make a cleanup when leaving?


Thank you

**Comment by lwfinger** [comment]
That is what I told you several comments ago.

**Comment by briansune** [comment]
@lwfinger 

Yes, but I am still not clear about the unrecoverable state.
Do this mean there is no way software can reset the interface or the UART to reattach the bluetooth UART Interface?

Thank you

**Comment by briansune** [comment]
@lwfinger 

I also tried the follow procedures:

Steps
1) hciconfig hci0 down
ps -a
kill PID rtk_hciattach

2) rmmod hci_uart.ko
3) insmod hci_uart.ko
4) rtk_hciattach -s xxxxxx

And result is the same unless physically reset the pin of 43 aka BT Power Down

Thank you

**Comment by lwfinger** [comment]
The problem is with the hciattach code, which is not properly restoring the state. As I have stated, I have no interest in debugging that code!
Without that fix, BT Power Down is the only solution. If you have a spare GPIO pin that is normally high, connecting that to BT Power Down and modifying hciattach to trigger that pin off would let you do it from code.

**Comment by briansune** [comment]
@lwfinger 

What you meant is that you are not sure software can restore a proper state UNLESS you go through a debugging process.
Correct me if I misunderstood.

And what you do sure that inserting a simple GPIO inside the hciattach to power cycle the BT Power down and up hardware pin is possible solution.
Correct me if I misunderstood again.

**Comment by lwfinger** [comment]
Yes to the first question.

Yes to the second as long as the GPIO output pin is connected to BT Power Down. That would do the same as your push button.

**Comment by briansune** [comment]
@lwfinger 

Okay, that also explain why most dtsi settings are with BT_DIS WIFI_DIS.
I will also make some modification on hardware.

Looks like the code itself have flush and all kinds of basic function but even with the driver of reset and power on functions the UART got stuck.

Again appreciate all the helps on this WIFI+BT chip.
I hope RTW88 will be much more stable on WIFI side.

Thank you

**Comment by briansune** [comment]
@lwfinger 

I had two H5 and H4 REALTEK datasheet.
But looks like it is old RTL8723BS.

Do you have any data can share out to check software reset is possible?
It is possible to add pin to reset bluetooth but GPIO constrains are a bit tight.
[UART interface BT controller initial guide-H5.pdf](https://github.com/lwfinger/rtl8723ds/files/12389958/UART.interface.BT.controller.initial.guide-H5.pdf)
[UART interface BT controller initial guide-H4.pdf](https://github.com/lwfinger/rtl8723ds/files/12389959/UART.interface.BT.controller.initial.guide-H4.pdf)
